@startuml

title __COPYRIGHT's Class Diagram__\n

  package edu.vccs.email.tas23466.copyright {
    class Question {
        - question : String
        - answersList : ArrayList<Answer>
        - selectedAnswer : int
        - numAnswers : int
        - backAvailable : boolean
        - specialCase : int
        + getSpecialCase()
        + setSpecialCase()
        + Question()
        + isBackAvailable()
        + setBackAvailable()
        + Question()
        + addAnswer()
        + getNumAnswers()
        + getAnswer()
        + getScore()
        + getNextQuestion()
        + getQuestion()
        + setQuestion()
        + getSelectedAnswer()
        + setSelectedAnswer()
    }
  }
  

  package edu.vccs.email.tas23466.copyright {
    class Answer {
        - answer : String
        - nextQuestion : String
        - score : int
        - Answer()
        + Answer()
        + getNextQuestion()
        + setNextQuestion()
    }
  }
  

  package edu.vccs.email.tas23466.copyright {
    class copyRightGUI {
        - dialog : JDialog
        - disclamerText : String
        - optionPane : JOptionPane
        - questionList : ArrayList<Question>
        {static} - backButton : JButton
        {static} - questionsPanel : JPanel
        {static} - buttons : JButton[]
        {static} - questionStack : Stack<Question>
        {static} - backButtonPanel : JPanel
        {static} - totalScore : int
        {static} - scoreStack : Stack<Integer>
        {static} - THRESHOLD : int
        + copyRightGUI()
        {static} + main()
        {static} - setQuestionText()
        {static} - setAnswersText()
        {static} + loadNextQuestion()
        {static} - backButton()
        {static} - loadQuestion()
        - loadFromFile()
    }
  }
  

  Question +-down- Answer
  copyRightGUI -up-|> JFrame



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
